(load (merge-pathnames "../lib/check.scm" (current-load-pathname)))

(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (empty?) (null? front-ptr))
    (define (front)
      (if (empty?)
          (error "FRONT called with an empty queue")
          (car front-ptr)))
    (define (insert! item)
      (let ((new-pair (list item)))
        (if (empty?)
            (set! front-ptr new-pair)
            (set-cdr! rear-ptr new-pair))
        (set! rear-ptr new-pair)
        dispatch))
    (define (delete!)
      (if (empty?)
          (error "DELETE! called with an empty queue")
          (begin (set! front-ptr (cdr front-ptr))
                 dispatch)))
    (define (dispatch m)
      (cond ((eq? m 'empty?) empty?)
            ((eq? m 'front) front)
            ((eq? m 'insert!) insert!)
            ((eq? m 'delete!) delete!)
            (else (error "Unknown operation -- QUEUE" m))))
    dispatch))

(define (empty-queue? queue) ((queue 'empty?)))
(define (front-queue queue) ((queue 'front)))
(define (insert-queue! queue item) ((queue 'insert!) item))
(define (delete-queue! queue) ((queue 'delete!)))

(define (drain-queue! queue)
  (if (empty-queue? queue)
      '()
      (let ((item (front-queue queue)))
        (delete-queue! queue)
        (cons item (drain-queue! queue)))))

(define q (make-queue))
(check (empty-queue? q) => #t)
(check-error (front-queue q))
(check-error (delete-queue! q))

(insert-queue! q 'a)
(insert-queue! q 'b)
(check (empty-queue? q) => #f)
(check (front-queue q) => 'a)
(check (front-queue (delete-queue! q)) => 'b)
(insert-queue! q 'c)
(check (drain-queue! q) => '(b c))
(check (empty-queue? q) => #t)

(insert-queue! q 'd)
(check (drain-queue! (insert-queue! q 'e)) => '(d e))

(define other (make-queue))
(insert-queue! other 1)
(check (empty-queue? q) => #t)
(check (front-queue other) => 1)
(check-error (q 'size))
