(load (merge-pathnames "../lib/check.scm" (current-load-pathname)))

;; The records are kept in a binary search tree ordered by key<?.  Two keys
;; are the same when neither is less than the other.  Inserting rebuilds
;; only the path from the root to the new record.

(define (make-tree key value left right) (list key value left right))
(define (tree-key tree) (car tree))
(define (tree-value tree) (cadr tree))
(define (tree-left tree) (caddr tree))
(define (tree-right tree) (cadddr tree))

(define (make-table key<?)
  (let ((root '()))
    (define (lookup key)
      (let search ((tree root))
        (cond ((null? tree) #f)
              ((key<? key (tree-key tree)) (search (tree-left tree)))
              ((key<? (tree-key tree) key) (search (tree-right tree)))
              (else (tree-value tree)))))
    (define (insert! key value)
      (define (adjoin tree)
        (cond ((null? tree)
               (make-tree key value '() '()))
              ((key<? key (tree-key tree))
               (make-tree (tree-key tree)
                          (tree-value tree)
                          (adjoin (tree-left tree))
                          (tree-right tree)))
              ((key<? (tree-key tree) key)
               (make-tree (tree-key tree)
                          (tree-value tree)
                          (tree-left tree)
                          (adjoin (tree-right tree))))
              (else
               (make-tree key value (tree-left tree) (tree-right tree)))))
      (set! root (adjoin root))
      'ok)
    (define (dispatch m)
      (cond ((eq? m 'lookup-proc) lookup)
            ((eq? m 'insert-proc!) insert!)
            (else (error "Unknown operation -- TABLE" m))))
    dispatch))

(define numbers (make-table <))
(define get (numbers 'lookup-proc))
(define put (numbers 'insert-proc!))

(check (get 1) => #f)
(for-each (lambda (key) (put key (* key key)))
          '(50 20 80 10 30 70 90 60 40))
(check (map get '(10 20 30 40 50 60 70 80 90))
       => '(100 400 900 1600 2500 3600 4900 6400 8100))
(check (get 55) => #f)
(check (get 5) => #f)
(check (get 95) => #f)

(put 30 'thirty)
(check (get 30) => 'thirty)
(check (get 40) => 1600)

(define words (make-table string<?))
((words 'insert-proc!) "pear" 3)
((words 'insert-proc!) "apple" 1)
((words 'insert-proc!) "zucchini" 5)
(check ((words 'lookup-proc) "apple") => 1)
(check ((words 'lookup-proc) "zucchini") => 5)
(check ((words 'lookup-proc) "banana") => #f)
(check-error (words 'delete!))
