(load "lib/check.scm")

(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch given-password m)
    (cond ((not (eq? given-password password))
           (lambda (amount) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  dispatch)

(define acc (make-account 100 'secret-password))
(check ((acc 'secret-password 'withdraw) 40) => 60)
(check ((acc 'some-other-password 'deposit) 50) => "Incorrect password")
(check ((acc 'secret-password 'deposit) 15) => 75)
(check ((acc 'secret-password 'withdraw) 100) => "Insufficient funds")
(check-error (acc 'secret-password 'transfer))
