(load "lib/check.scm")
(load "ch3/lib/constraints.scm")

(define (squarer a b)
  (define (process-new-value)
    (cond ((has-value? b)
           (if (< (get-value b) 0)
               (error "square less than 0 -- SQUARER" (get-value b))
               (set-value! a (sqrt (get-value b)) me)))
          ((has-value? a)
           (set-value! b (square (get-value a)) me))))
  (define (process-forget-value)
    (forget-value! a me)
    (forget-value! b me)
    (process-new-value))
  (define (me request)
    (cond ((eq? request 'I-have-a-value) (process-new-value))
          ((eq? request 'I-lost-my-value) (process-forget-value))
          (else (error "Unknown request -- SQUARER" request))))
  (connect a me)
  (connect b me)
  me)

(define a (make-connector))
(define b (make-connector))
(squarer a b)

(set-value! b 16 'user)
(check (get-value a) => 4)

(forget-value! b 'user)
(check (has-value? a) => #f)
(set-value! a -3 'user)
(check (get-value b) => 9)

(forget-value! a 'user)
(check (has-value? b) => #f)
(check-error (set-value! b -4 'user))
