(load "lib/check.scm")

(define (make-account balance password call-the-cops)
  (define max-wrong-attempts 7)
  (define wrong-attempts 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (reject amount)
    (set! wrong-attempts (+ wrong-attempts 1))
    (if (> wrong-attempts max-wrong-attempts)
        (call-the-cops)
        "Incorrect password"))
  (define (lookup m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT" m))))
  (define (dispatch given-password m)
    (if (eq? given-password password)
        (begin (set! wrong-attempts 0)
               (lookup m))
        reject))
  dispatch)

(define (cops) "Cops called")

(define (try-wrong-password acc times)
  (let ((result ((acc 'guess 'withdraw) 10)))
    (if (= times 1)
        result
        (try-wrong-password acc (- times 1)))))

(define acc (make-account 100 'secret cops))
(check (try-wrong-password acc 7) => "Incorrect password")
(check (try-wrong-password acc 1) => "Cops called")

(define acc2 (make-account 100 'secret cops))
(try-wrong-password acc2 7)
(check ((acc2 'secret 'withdraw) 10) => 90)
(check (try-wrong-password acc2 1) => "Incorrect password")
