(load "lib/check.scm")
(load "ch3/lib/serializers.scm")

(define (make-account-and-serializer balance)
  (define (withdraw amount)
    (let ((current (atomic balance)))
      (atomic (set! balance (- current amount)))))
  (define (deposit amount)
    (let ((current (atomic balance)))
      (atomic (set! balance (+ current amount)))))
  (let ((balance-serializer (make-serializer)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'balance) (atomic balance))
            ((eq? m 'serializer) balance-serializer)
            (else (error "Unknown request -- MAKE-ACCOUNT" m))))
    dispatch))

(define (make-account balance)
  (let ((account (make-account-and-serializer balance)))
    (lambda (m)
      (if (memq m '(withdraw deposit))
          ((account 'serializer) (account m))
          (account m)))))

(define (exchange account1 account2)
  (let ((difference (- (account1 'balance) (account2 'balance))))
    ((account1 'withdraw) difference)
    ((account2 'deposit) difference)))

(define (serialized-exchange account1 account2)
  (let ((serializer1 (account1 'serializer))
        (serializer2 (account2 'serializer)))
    ((serializer1 (serializer2 exchange)) account1 account2)))

(define (final-balances make-account exchange)
  (possible-outcomes
   (lambda ()
     (let ((a (make-account 10))
           (b (make-account 20))
           (c (make-account 30)))
       (parallel-execute (lambda () (exchange a b))
                         (lambda () (exchange b c)))
       (map (lambda (account) (account 'balance)) (list a b c))))))
