(load (merge-pathnames "../lib/check.scm" (current-load-pathname)))
(load (merge-pathnames "lib/serializers.scm" (current-load-pathname)))

;; Both semaphores guard the count of free places with a mutex (or a cell)
;; and make waiting processes queue on a gate, which is closed while no
;; place is free: the last process to take a place leaves it closed, and
;; the release that frees a place again opens it.  So nobody waits by
;; repeatedly re-checking the count.

;; a. In terms of mutexes

(define (make-semaphore n)
  (if (< n 1)
      (error "A semaphore needs at least one place -- MAKE-SEMAPHORE" n))
  (let ((free n)
        (gate (make-mutex))
        (mutex (make-mutex)))
    (define (acquire)
      (gate 'acquire)
      (mutex 'acquire)
      (set! free (- free 1))
      (if (> free 0)
          (gate 'release))
      (mutex 'release))
    (define (release)
      (mutex 'acquire)
      (set! free (+ free 1))
      (if (= free 1)
          (gate 'release))
      (mutex 'release))
    (define (the-semaphore m)
      (cond ((eq? m 'acquire) (acquire))
            ((eq? m 'release) (release))
            (else (error "Unknown request -- SEMAPHORE" m))))
    the-semaphore))

;; b. In terms of atomic test-and-set! operations

(define (make-cell-semaphore n)
  (if (< n 1)
      (error "A semaphore needs at least one place -- MAKE-CELL-SEMAPHORE" n))
  (let ((free n)
        (gate (list false))
        (lock (list false)))
    (define (wait-for cell)
      (if (test-and-set! cell)
          (wait-for cell)))
    (define (acquire)
      (wait-for gate)
      (wait-for lock)
      (set! free (- free 1))
      (if (> free 0)
          (clear! gate))
      (clear! lock))
    (define (release)
      (wait-for lock)
      (set! free (+ free 1))
      (if (= free 1)
          (clear! gate))
      (clear! lock))
    (define (the-semaphore m)
      (cond ((eq? m 'acquire) (acquire))
            ((eq? m 'release) (release))
            (else (error "Unknown request -- CELL-SEMAPHORE" m))))
    the-semaphore))

;; The most processes ever inside at once, over all orders of their steps.
(define (most-inside make-semaphore n processes)
  (possible-outcomes
   (lambda ()
     (let ((semaphore (make-semaphore n))
           (inside 0)
           (most 0))
       (define (use-place)
         (semaphore 'acquire)
         (atomic (set! inside (+ inside 1))
                 (set! most (max most inside)))
         (atomic (set! inside (- inside 1)))
         (semaphore 'release))
       (apply parallel-execute (make-list processes use-place))
       most))))

(define (check-semaphore make-semaphore)
  (check (most-inside make-semaphore 1 2) => '(1))
  (check (most-inside make-semaphore 1 3) => '(1))
  (check (most-inside make-semaphore 2 2) (=> same-set?) '(1 2))
  (let ((semaphore (make-semaphore 2)))
    (semaphore 'acquire)
    (semaphore 'acquire)
    (semaphore 'release)
    (semaphore 'acquire)
    (check-error (semaphore 'acquire)))
  (check-error (make-semaphore 0)))

(check-semaphore make-semaphore)
(check-semaphore make-cell-semaphore)
