(load (merge-pathnames "../lib/check.scm" (current-load-pathname)))
(load (merge-pathnames "4.6.scm" (current-load-pathname)))
(load (merge-pathnames "lib/analyze.scm" (current-load-pathname)))

(define analyze-without-let analyze)

(define (analyze exp)
  (if (let? exp)
      (analyze (let->combination exp))
      (analyze-without-let exp)))

(check (analyzing-interpret '(let ((x 1) (y 2)) (+ x y))) => 3)
(check (analyzing-interpret '(let () 5)) => 5)
(check (analyzing-interpret '(define x 10)
                            '(let ((x 1) (y x)) (list x y)))
       => '(1 10))
(check (analyzing-interpret '(define (sum-to n)
                               (let ((half (/ n 2)))
                                 (* half (+ n 1))))
                            '(sum-to 10))
       => 55)
(check (analyzing-interpret '(define (make-counter)
                               (let ((count 0))
                                 (lambda ()
                                   (set! count (+ count 1))
                                   count)))
                            '(define counter (make-counter))
                            '(counter)
                            '(counter))
       => 2)
