(load (merge-pathnames "../lib/check.scm" (current-load-pathname)))
(load (merge-pathnames "lib/amb.scm" (current-load-pathname)))

(define env
  (amb-environment
   '(define (a-free-place taken)
      (let ((place (amb 1 2 3 4 5)))
        (require (not (memq place taken)))
        place))
   '(define (exactly-one? p q)
      (if p (not q) q))
   '(define (examination-results)
      (let* ((betty (a-free-place '()))
             (ethel (a-free-place (list betty)))
             (joan (a-free-place (list betty ethel)))
             (kitty (a-free-place (list betty ethel joan)))
             (mary (a-free-place (list betty ethel joan kitty))))
        (require (exactly-one? (= kitty 2) (= betty 3)))
        (require (exactly-one? (= ethel 1) (= joan 2)))
        (require (exactly-one? (= joan 3) (= ethel 5)))
        (require (exactly-one? (= kitty 2) (= mary 4)))
        (require (exactly-one? (= mary 4) (= betty 1)))
        (list (list 'betty betty)
              (list 'ethel ethel)
              (list 'joan joan)
              (list 'kitty kitty)
              (list 'mary mary))))))

(check (amb-collect '(exactly-one? true false) env) => '(#t))
(check (amb-collect '(exactly-one? true true) env) => '(#f))
(check (amb-collect '(exactly-one? false false) env) => '(#f))

(check (amb-collect '(examination-results) env)
       => '(((betty 3) (ethel 5) (joan 2) (kitty 1) (mary 4))))
