(load (merge-pathnames "../lib/check.scm" (current-load-pathname)))
(load (merge-pathnames "lib/mceval.scm" (current-load-pathname)))

(define (let? exp) (tagged-list? exp 'let))
(define (let-bindings exp) (cadr exp))
(define (let-body exp) (cddr exp))
(define (binding-variable binding) (car binding))
(define (binding-value binding) (cadr binding))
(define (let-variables exp) (map binding-variable (let-bindings exp)))
(define (let-inits exp) (map binding-value (let-bindings exp)))

(define (make-let bindings body)
  (cons 'let (cons bindings body)))

(define (let->combination exp)
  (cons (make-lambda (let-variables exp) (let-body exp))
        (let-inits exp)))

(define (mc-eval exp env)
  (cond ((self-evaluating? exp) exp)
        ((variable? exp) (lookup-variable-value exp env))
        ((quoted? exp) (text-of-quotation exp))
        ((assignment? exp) (eval-assignment exp env))
        ((definition? exp) (eval-definition exp env))
        ((if? exp) (eval-if exp env))
        ((lambda? exp)
         (make-procedure (lambda-parameters exp)
                         (lambda-body exp)
                         env))
        ((begin? exp)
         (eval-sequence (begin-actions exp) env))
        ((cond? exp) (mc-eval (cond->if exp) env))
        ((let? exp) (mc-eval (let->combination exp) env))
        ((application? exp)
         (mc-apply (mc-eval (operator exp) env)
                   (list-of-values (operands exp) env)))
        (else
         (error "Unknown expression type -- EVAL" exp))))

(check (let->combination '(let ((x 1) (y 2)) (display x) (+ x y)))
       => '((lambda (x y) (display x) (+ x y)) 1 2))
(check (interpret '(let ((x 1) (y 2)) (+ x y))) => 3)
(check (interpret '(let () 5)) => 5)
(check (interpret '(define x 10)
                  '(let ((x 1) (y x)) (list x y)))
       => '(1 10))
(check (interpret '(let ((x 1))
                     (let ((x (+ x 1)))
                       (* x 10))))
       => 20)
